### PR TITLE
Dice Scoring Review

### PR DESCRIPTION
**Pull request by lnestor**
Nice job - I finally had to learn what the `inject` method does! My changes are mostly personal preference. I think taking one line to initialize the hash creates less clutter than making an empty hash on one line and looping through it on the next. If you wanted to loop through each and do it all in one line, you could use the `tap` method like this:

```
number_counts = {}.tap { |hash| (1..6).each { |die| hash[die] = 0 } }
```

Though that is much more dense than both of the other ways.

### CODE REVIEW

**Comment by danclark5** [comment]
Nice. Thanks for the feedback. I'll have to look at the tap method tomorrow morning to understand what's going on there.

**Comment by danclark5** [comment]
Tap is pretty neat. I like that it'll take an object and do something with it. It took me a bit to get up to speed on it.

That said, I realized another way. First, this is how I'd do it in Python:

`number_counts = {die:0 for die in range(1,7)}`

Originally, I tried to mimic this, but I couldn't figure out how to do it in one step. The tap method you used convinced me that there probably is a way, and below is what I was able to whip up.

`number_counts = Hash[(1..6).map { |die| [die, 0] }]`

The way I see it, we're building an array of elements and then wrapping it with a hash. This is similar to the Python approach. Anyway, let me know if this is a weird way of going about it or if there is a better way.

Also, is there a difference between map and collect? [stackoverflow says no.](https://stackoverflow.com/a/5254764/1382818)

**Comment by lnestor** [comment]
Tap is a weird concept to get used to. I first encountered it in our codebase doing something like the following:

```
patient_data = {
  first_name: question_answer(:first_name),
  last_name: question_answer(:last_name)
}.tap do |h|
  h[:address] = question_answer(:address) if question_answer(:address)
end
```
Since we can't do conditionals in the hash declaration, we use the tap method to be able to use conditionals. 

Yeah, looks like map and collect are the same thing. The source code for both of them is the same exact function. In reality, I don't know many ruby methods because there are so many. If I am doing something on an array, I always have to look up the list of array methods and find the best one. The simple ones like `#each` and `#map` are easy to memorize, but then there's some like `#compact` that are hardly used but still useful in certain situations.

To answer your question, being clever about how to build the hash in one line is nice and fun to code, but being clear is more useful to other developers. So, I'd probably go with either your first solution or explicitly initializing each value since there are only 6. It takes a few seconds to understand what either of those ways are doing, but for using `#tap` and `#map`, the next developer might have to look up what those methods do to understand the code.

**Comment by danclark5** [comment]
That all makes sense, thanks for the clarification. I'll leave the code as is and close this PR. 

The conversation has been great. I haven't really had someone to bounce ideas off of at work, so I really appreciate this.

**Pull request closed without merging**
